plugins {
    id 'java'
}

group = 'com.simplerender'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.graalvm.js:js:24.2.1'
    implementation 'org.graalvm.js:js-scriptengine:24.2.1'
    implementation 'org.webjars.npm:draco3d:1.5.7'
    implementation 'org.pf4j:pf4j:3.12.0'
    annotationProcessor 'org.pf4j:pf4j:3.12.0'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation project(':')
}

jar {
    manifest {
        attributes(
            'Plugin-Id': 'gltf-importer',
            'Plugin-Class': 'com.simplerender.plugin.gltf.GltfImporterPlugin',
            'Plugin-Version': project.version,
            'Plugin-Provider': 'simple-render'
        )
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
